-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1:3306
-- Tiempo de generación: 05-01-2022 a las 00:09:09
-- Versión del servidor: 5.7.31
-- Versión de PHP: 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `news`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `news`
--

DROP TABLE IF EXISTS `news`;
CREATE TABLE IF NOT EXISTS `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titre` varchar(150) NOT NULL,
  `pubDate` date NOT NULL,
  `description` varchar(2500) NOT NULL,
  `link` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1002 DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `news`
--

INSERT INTO `news` (`id`, `titre`, `pubDate`, `description`, `link`) VALUES
(1, 'Fresh batch of games hit PS Plus and PS Now for January', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-15-44/-1641311072416.jpg/EG11/resize/1200x-1/2183167.jpg\" alt=\"\"/><p>A fresh batch of games will be available for PS Plus subscribers from today.</p><p>First up is Persona 5: Strikers. Released last year for PS4, it\'s a follow-up to the critically acclaimed JRPG Persona 5 but with musuu-style combat alongside its teen drama.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-fresh-batch-of-games-hit-ps-plus-and-ps-now-for-january\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-fresh-batch-of-games-hit-ps-plus-and-ps-now-for-january'),
(2, 'Star Wars: Jedi Fallen Order headlines January Amazon Prime games', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-15-17/-1641309422476.jpg/EG11/resize/1200x-1/2183157.jpg\" alt=\"\"/><p>Respawn\'s well-received Star Wars: Jedi Fallen Order is available to claim and keep via Origin this month if you are an Amazon Prime subscriber. </p><p>Copies of strategy epic Total War: Warhammer plus shooter World War Z: Aftermath are both also available to claim via the Epic Game Store.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-star-wars-jedi-fallen-order-headlines-january-amazon-prime-games\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-star-wars-jedi-fallen-order-headlines-january-amazon-prime-games'),
(3, 'GoldenEye 007 Xbox achievements leak points to new port', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-14-23/-1641306213366.jpg/EG11/resize/1200x-1/2183121.jpg\" alt=\"\"/><p>Rare\'s legendary GoldenEye 007 looks set to return - as detailed by a newly-leaked set of Xbox achievements.</p><p>The achievement list, which was scooped off Microsoft\'s servers by <a href=\"https://www.trueachievements.com/game/GoldenEye-007/achievements\">True Achievements</a>, includes 55 new awards and 1000 Gamerscore for completing the game\'s campaign and playing its various multiplayer modes. Achievement artwork even includes screenshots from the classic James Bond shooter.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-goldeneye-007-xbox-achievements-leak-points-to-new-port\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-goldeneye-007-xbox-achievements-leak-points-to-new-port'),
(4, 'New Samsung TVs will include cloud gaming and NFT support', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-14-45/-1641307508829.jpg/EG11/resize/1200x-1/2183138.jpg\" alt=\"\"/><p>The 2022 range of Samsung Neo QLED televisions will include a Gaming Hub that supports cloud streaming and NFTs.</p><p>Cloud game libraries from Stadia, GeForce Now and Utomik will be featured, with \"more to come\". Games can be played simply by pairing a compatible controller.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-new-samsung-tvs-will-include-cloud-gaming-and-nft-support\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-new-samsung-tvs-will-include-cloud-gaming-and-nft-support'),
(5, 'Mass Effect: Legendary Edition leads January Xbox Game Pass additions', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-14-18/-1641305907065.jpg/EG11/resize/1200x-1/2183118.jpg\" alt=\"\"/><p>Mass Effect: Legendary Edition is among the games coming to Xbox Game Pass this month.</p><p>The sci-fi trilogy remaster will hit the service on console and PC (via EA Play) on 6th January, including all three games and DLC.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-mass-effect-legendary-edition-leads-game-pass-additions-this-january\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-mass-effect-legendary-edition-leads-game-pass-additions-this-january'),
(6, 'Xbox Series X/S stock: where to buy Microsoft\'s new console', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2020/articles/2020-09-21-15-09/xbox_series_x_s_pre_order_packaging.jpg/EG11/resize/1200x-1/2123324.jpg\" alt=\"\"/><p><strong>Latest (04.01.21):</strong> In the UK, the Xbox Series X was in stock at <a href=\"https://amzn.to/3mV5AFe\" rel=\"sponsored noopener\" target=\"_blank\">Amazon UK</a> for Â£449.99.</p><p>Keep your eyes on the retailer list below for the latest stock updates on Xbox Series X and deals info for the Series S.</p><p><a href=\"https://www.eurogamer.net/articles/xbox-series-x-s-stock-where-to-buy\">Read more</a></p>', 'https://www.eurogamer.net/articles/xbox-series-x-s-stock-where-to-buy'),
(7, 'Driveclub director\'s next game won\'t be a racer', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-12-29/-1641299395092.jpg/EG11/resize/1200x-1/2183077.jpg\" alt=\"\"/><p>\nThe director of PlayStation 4 exclusive Driveclub is working on a new project, but it won\'t be a racing game.</p><p>Paul \"Rushy\" Rustchynsky tweeted to say the project will be announced this year and will come from the new Avalanche studio in Liverpool that opened last year.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-driveclub-directors-next-game-wont-be-a-racer\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-driveclub-directors-next-game-wont-be-a-racer'),
(8, 'Former team members criticise BioShock creator Ken Levine\'s inability to actually release a game', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-12-26/-1641299190312.jpg/EG11/resize/1200x-1/2183076.jpg\" alt=\"\"/><p><a href=\"https://www.bnnbloomberg.ca/the-next-video-game-from-bioshock-s-auteur-is-in-development-hell-1.1702538\" target=\"_blank\">Bloomberg</a> has reported that, after nearly eight years of development, the next project from BioShock creator Ken Levine is in development hell.</p><p>The report is based on interviews with several of Levine\'s former colleagues at Ghost Story Games, the small studio set up by Levine following the launch of BioShock Infinite and his decision to subsequently shutter former studio Irrational Games.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-former-team-members-criticise-bioshock-creator-ken-levines-inability-to-actually-release-a-game\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-former-team-members-criticise-bioshock-creator-ken-levines-inability-to-actually-release-a-game'),
(9, 'Square Enix president believes NFTs and blockchain tech will be a \"major trend\" this year', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-11-43/-1641296590918.jpg/EG11/resize/1200x-1/2183062.jpg\" alt=\"\"/><p>Square Enix president Yosuke Matsuda has published a letter in which he expresses hope that NFTs and blockchain technology will become a \"major trend\" in gaming.</p><p>In a <a href=\"https://www.hd.square-enix.com/eng/news/2022/html/a_new_years_letter_from_the_president_2.html\">New Year\'s letter</a>, Matsuda expressed what he believes will be major areas of growth for the industry in 2022, including cloud gaming, AI, and blockchain games.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-square-enix-president-believes-nfts-and-blockchain-tech-will-be-a-major-trend-this-year\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-square-enix-president-believes-nfts-and-blockchain-tech-will-be-a-major-trend-this-year'),
(10, 'Report details Rockstar\'s axed plans for Bully 2', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-11-25/-1641295505483.jpg/EG11/resize/1200x-1/2183058.jpg\" alt=\"\"/><p>Fresh details have come to light of the once-planned sequel to Bully, Rockstar\'s brilliant schoolyard sim, as part of a new <a href=\"https://www.gameinformer.com/2021/12/30/the-version-of-bully-2-youll-never-get-to-play\">Game Informer</a> report.</p><p>Bully 2 would have featured a vastly-expanded playable world three times the size of the original game, where every building could have been entered (legally or via forced entry). </p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-report-details-rockstars-axed-plans-for-bully-2\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-report-details-rockstars-axed-plans-for-bully-2'),
(11, 'Final Fantasy 16 news due this spring', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-10-58/-1641293885027.jpg/EG11/resize/1200x-1/2183047.jpg\" alt=\"\"/><p>The next big reveal for Final Fantasy 16 will be in the spring, following delays due to COVID-19.</p><p>Producer Naoki Yoshida, who\'s also been busy with the recently released <a href=\"https://www.eurogamer.net/articles/2021-12-21-final-fantasy-14-is-a-storytelling-masterpiece\">Endwalker expansion</a> for Final Fantasy 14, wrote an <a href=\"https://na.finalfantasyxvi.com/\">update on the game\'s website</a> explaining it\'s been delayed by almost half a year.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-final-fantasy-16-news-is-due-this-spring\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-final-fantasy-16-news-is-due-this-spring'),
(12, 'Riot Games agrees $100m gender discrimination settlement', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-10-53/-1641293624490.jpg/EG11/resize/1200x-1/2183040.jpg\" alt=\"\"/><p>League of Legends maker Riot Games has agreed a $100m (Â£74m) settlement to finally end its <a href=\"https://www.eurogamer.net/articles/2019-08-23-riot-games-settles-class-action-lawsuit-alleging-sexual-harassment-gender-discrimination\">long-running gender discrimination lawsuit</a>.</p><p>The settlement, announced at the end of December, brings to a close the class action suit filed by employees back in 2018. </p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-riot-games-agrees-usd100m-gender-discrimination-settlement\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-riot-games-agrees-usd100m-gender-discrimination-settlement'),
(13, 'Off Topic: Hedra\'s astonishing page layouts revel in their giddy sense of invention', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-09-06/-1641287194380.jpg/EG11/resize/1200x-1/2183000.jpg\" alt=\"\"/><p>My copy of Hedra is a wonderfully odd thing. It\'s tabloid size, and it\'s printed on newspaper and has no staples. It feels a bit like an old student magazine. Inside, it is sheer poise and artistry and imagination. </p><p>I first read about Hedra in a <a href=\"https://www.polygon.com/comics/2020/5/8/21252344/new-comics-sci-fi-space-image-jesse-lonergan-art-hedra\" target=\"_blank\">Polygon article</a> back in 2020. A one-shot comic book with an astonishing visual conceit: each page is based around an arrangement of 35 panels - five by seven. Wordlessly, these panels come together to tell a story that spans the galaxy.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-off-topic-hedras-astonishing-page-layouts-revel-in-their-giddy-sense-of-invention\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-off-topic-hedras-astonishing-page-layouts-revel-in-their-giddy-sense-of-invention'),
(14, 'Best Nintendo Switch deals January 2022', '2022-01-01', '<img src=\"https://images.gnwcdn.com/2020/articles/2020-04-03-11-47/best_nintendo_switch_bundle_deals_header.jpg/EG11/resize/1200x-1/2089106.jpg\" alt=\"\"/><p>Whether you\'re looking for the latest deals on Nintendo Switch, <a href=\"https://www.eurogamer.net/articles/2021-04-13-theres-a-new-nintendo-switch-lite-coloured-blue\">Nintendo Switch Lite</a> and <a href=\"https://www.eurogamer.net/articles/digitalfoundry-2021-nintendo-switch-oled-model-review-an-excellent-premium-upgrade\">Nintendo Switch OLED</a> consoles or you\'re trying to save money on the best-selling titles, you\'ll find all of the best Nintendo Switch deals right here.</p><p>Below, you\'ll find our picks for the top Nintendo Switch bundles right now, as well as offers on the Switch Lite and Switch OLED. If you\'re not already familiar with the key differences between the three consoles, the Switch Lite is a hand-held only version of the Nintendo Switch, while the Nintendo Switch OLED comes with an improved OLED screen and other minor enhancements.</p><p><a href=\"https://www.eurogamer.net/articles/best-nintendo-switch-bundle-deals\">Read more</a></p>', 'https://www.eurogamer.net/articles/best-nintendo-switch-bundle-deals'),
(15, 'Best PS4 deals for games and accessories in January 2022', '2022-01-01', '<img src=\"https://images.gnwcdn.com/2021/articles/2021-12-09-19-42/spider_man_miles_morales_00.jpg/EG11/resize/1200x-1/2180273.jpg\" alt=\"\"/><p>Now that the PS5 has settled in as the new console generation, you might think it would be a good time to make a saving on a PS4. However, stock shortages during the pandemic and the fact that all but the PS4 slim models have been officially discontinued by Sony, means new PS4 consoles are actually just as hard to find. On the other hand, those who have a console already can still take advantage of some amazing deals on PS4 games and accessories we\'ve found here.</p><p> Some of this month\'s highlights include <a href=\"https://www.thegamecollection.net/persona-5-royal-standard-edition-ps4\" rel=\"sponsored noopener\" target=\"_blank\"> Persona 5 Royal for Â£17.95</a>, <a href=\"https://www.base.com/buy/product/the-witcher-3-wild-hunt-game-of-the-year-edition-ps4/dgc-w3gotyps4.htm\" rel=\"sponsored noopener\" target=\"_blank\">The Witcher 3: Wild Hunt Game of the Year Edition for Â£18.09</a> and a  <a href=\"https://www.shopto.net/en/dls55907-playstation-plus-12-month-membership-p113292/\" rel=\"sponsored noopener\" target=\"_blank\">12 month PlayStation Plus membership for for Â£41.85</a>.</p><p><a href=\"https://www.eurogamer.net/articles/best-ps4-games-accessories-deals\">Read more</a></p>', 'https://www.eurogamer.net/articles/best-ps4-games-accessories-deals'),
(16, 'Best PS5 deals January 2022', '2022-01-01', '<img src=\"https://images.gnwcdn.com/2021/articles/2021-01-11-15-23/best-playstation-game-deals-for-january-2021-1610378632665.jpg/EG11/resize/1200x-1/2154835.jpg\" alt=\"\"/><p> The console has now been out for just over a year (and still frankly difficult to get hold of) but that hasn\'t stopped us from trying to gather all the best PS5 deals across games, accessories and more.</p><p>If you\'ve been fortunate to get your hands on Sony\'s cutting-edge console then of course you\'ll want some games to play on it besides the excellent preinstalled Astro\'s Playroom. While we\'re still in the early years of cross-gen releases, there\'s nonetheless been a wide range of games available - whether via download or disc - including renowned exclusives, indie darlings and major blockbusters. We\'ll be updating this page regularly to keep you instantly in the know on where to find the best PS5 deals as we close out 2021. If you\'re looking for gift inspiration, you should also check out our <a href=\"https://www.eurogamer.net/articles/gamers-gift-guide\"> gamer gift guide</a>.</p><p><a href=\"https://www.eurogamer.net/articles/best-ps5-deals\">Read more</a></p>', 'https://www.eurogamer.net/articles/best-ps5-deals'),
(17, 'Best Xbox deals for January 2022', '2022-01-01', '<img src=\"https://images.gnwcdn.com/2021/articles/2021-01-11-16-46/best_xbox_deals_series_x_series_s_header.jpg/EG11/resize/1200x-1/2131849.jpg\" alt=\"\"/><p>The new consoles are now firmly here and present (despite stock not being quite as easy to find), and whether you\'ve managed to grab a new Xbox already, are getting ready to grab one soon or you\'re simply building on your lovable library of Xbox One games, there\'s a lot to pick from. And though the new consoles aren\'t likely to be discounted soon, the fact that most of the games will carry over means you can grab a deal on bestsellers now, or stack up on the best subscriptions like Xbox Game Pass or Xbox Live Gold for the near future.</p><p>So whether you\'re looking for a new Xbox Series X or S, Xbox games, controllers, Game Pass Ultimate subscriptions or accessories,  there are plenty of great deals to tuck into this month. If you\'re looking for gift inspiration, you should also check out our <a href=\"https://www.eurogamer.net/articles/gamers-gift-guide\"> Christmas gift guide</a>.</p><p><a href=\"https://www.eurogamer.net/articles/best-xbox-deals-series-x-series-s\">Read more</a></p>', 'https://www.eurogamer.net/articles/best-xbox-deals-series-x-series-s'),
(18, 'The best full fibre (FTTP) broadband deals January 2022', '2022-01-01', '<img src=\"https://images.gnwcdn.com/2020/articles/2020-08-18-12-23/full_fibre_broadband_deals.jpg/EG11/resize/1200x-1/2110835.jpg\" alt=\"\"/><p>Full fibre broadband is here. Over the last year, the availability of this much-faster fibre to the premises (FTTP) broadband technology has grown significantly across the UK. There\'s still a long way to go before it\'s more universally available, but there\'s growing competition between BT, EE, Sky, Vodafone and more to offer incredible download speeds. These providers are seeking to entice customers to switch to the new service with better offers. If you\'re lucky enough to be within the coverage area and want to try it for yourself, here are some of the best full fibre broadband deals out there this month.</p><p>On this page:</p><p><a href=\"https://www.eurogamer.net/articles/full-fibre-broadband-deals\">Read more</a></p>', 'https://www.eurogamer.net/articles/full-fibre-broadband-deals'),
(19, 'Eurogamer readers\' top 50 games of 2021', '2021-12-31', '<img src=\"https://images.gnwcdn.com/2021/articles/2021-12-31-11-46/eurogamer-readers-top-50-games-of-2021-1640951181021.jpg/EG11/resize/1200x-1/2181946.jpg\" alt=\"\"/><p>2021 has been another extremely unusual year, so hopefully it\'s a bit of a treat to end it in our usual way - with the top fifty games of the last twelve months, as chosen by you. </p><p>What we said: \"Chalk this one up as another slightly botched Battlefield launch - only at least this time it\'s been botched in new and interesting ways.\"</p><p><a href=\"https://www.eurogamer.net/articles/2021-12-31-eurogamer-readers-top-50-games-of-2021\">Read more</a></p>', 'https://www.eurogamer.net/articles/2021-12-31-eurogamer-readers-top-50-games-of-2021'),
(20, 'Save Â£10 on the collector\'s edition of Taiko No Tatsujin for Nintendo Switch', '2021-12-30', '<p>Fancy playing something different on your Nintendo Switch? The collector\'s edition of Taiko No Tatsujin: Drum \'n\' Fun on the Nintendo Switch is now Â£80 from Argos.</p><p>The collector\'s edition of the game includes the trademark taiko drum along with two beaters. This isn\'t a bad price for the game considering most retailers, including Amazon, are selling it for over Â£100. And if you hold onto this, it should only go up in price as the drums become harder to find.</p><p><a href=\"https://www.eurogamer.net/articles/2021-12-30-save-gbp10-on-the-collectors-edition-of-taiko-no-tatsujin-for-nintendo-switch\">Read more</a></p>', 'https://www.eurogamer.net/articles/2021-12-30-save-gbp10-on-the-collectors-edition-of-taiko-no-tatsujin-for-nintendo-switch'),
(21, 'Eurogamer\'s game of the year isâ€¦', '2021-12-30', '<img src=\"https://images.gnwcdn.com/2021/articles/2021-12-20-12-55/eurogamers-game-of-the-year-is-1640004946697.jpg/EG11/resize/1200x-1/2181565.jpg\" alt=\"\"/><p>It has been 12 months, or as some might say <em>a year</em>, and there have been video games. In fact, looking at Eurogamer\'s top 10 of the year as well as your own top 50, it\'s clear there have been some mighty fine video games too, undermining the impression that 2021\'s been something of a lull for the industry. </p><p>Yes, there might not have been so many big ticket titles, and yes we\'re having to wait until next year for the likes of Breath of the Wild\'s sequel, Starfield, Elden Ring and Horizon Forbidden West, but we\'ve not been short of crowd pleasing headliners. </p><p><a href=\"https://www.eurogamer.net/articles/2021-12-30-eurogamers-game-of-the-year-is\">Read more</a></p>', 'https://www.eurogamer.net/articles/2021-12-30-eurogamers-game-of-the-year-is'),
(22, 'Save over Â£30 on the Logitech G915 Lightspeed TKL Wireless Keyboard', '2021-12-29', '<img src=\"https://images.gnwcdn.com/2021/articles/2021-12-29-18-24/logitech_g915_keyboard.jpg/EG11/resize/1200x-1/2182682.jpg\" alt=\"\"/><p>With Christmas all wrapped up for this year, we now look to the beginning of a new year. 2022 is right around the corner, and so is another year of keyboard clicks and gaming. To ring in the next 365 days and all the gaming goodness they\'re likely to bring, if you\'re a PC gamer, you may be looking for new ways to upgrade and enhance your powerhouse setup.</p><p>If it happens to be a new keyboard that\'s in your sights, look no further than this deal available on the <a href=\"https://www.amazon.co.uk/Logitech-Tenkeyless-LIGHTSPEED-Mechanical-LIGHTSYNC/dp/B07W6JQ1KQ?tag=eurgam-dec-21\" rel=\"sponsored noopener\" target=\"_blank\">Logitech G915 Lightspeed TKL wireless gaming keyboard available for Â£166 at Amazon</a>, a Â£33 saving on its usual price.</p><p><a href=\"https://www.eurogamer.net/articles/2021-12-29-save-more-than-gbp30-on-the-logitech-g915-lightspeed-tkl-wireless-keyboard\">Read more</a></p>', 'https://www.eurogamer.net/articles/2021-12-29-save-more-than-gbp30-on-the-logitech-g915-lightspeed-tkl-wireless-keyboard'),
(23, '2021 in review: Finding games to play together', '2021-12-29', '<p><em>Hello! Over the next few days we\'re going to be going back over some of our favourite games and moments and themes and whatnot from this very strange year. We hope you enjoy looking back with us!</em></p><p>It\'s not easy finding games to play with other people in the same house. You\'ll know this if you\'ve tried. It\'s one of the reasons I was so impressed with It Takes Two earlier in the year. It\'s not only playable in local co-op but entirely designed for it, which means gameplay solutions <em>require</em> two people rather than <em>can also be played</em> by two people. For instance, one person throws giant nails into a wall while the other person uses the head of a giant claw hammer to swing on them. It\'s just one example and there are many - the ideas keep changing and they keep coming - and it\'s brilliant. It Takes Two is probably the best example of dedicated local co-op gaming in years, if not ever. </p><p><a href=\"https://www.eurogamer.net/articles/2021-12-14-finding-games-to-play-together\">Read more</a></p>', 'https://www.eurogamer.net/articles/2021-12-14-finding-games-to-play-together'),
(24, 'Save Â£200 on this packed Asus gaming laptop with an RTX 3060', '2021-12-29', '<img src=\"https://images.gnwcdn.com/2021/articles/2021-12-29-14-27/asus_rog_strix.jpg/EG11/resize/1200x-1/2182644.jpg\" alt=\"\"/><p>With desktop GPUs still hard to come by at standard retail prices, it may be that a gaming laptop is your best bet for PC gaming. And there are some great deals to be had when going portable: the Asus ROG Strix 15 is <a href=\"https://www.amazon.co.uk/ASUS-G513QM-GeForce-9-5900HX-Windows/dp/B09C1VH35S/?tag=eurgam-dec-21\" rel=\"sponsored noopener\" target=\"_blank\">currently down to Â£1200 on Amazon</a>, a saving of Â£200.</p><p>The two-hit headline for this laptop is that it packs a high-end Nvidia GeForce RTX 3060 graphics card with an AMD Ryzen 9 5900HX processor. This means you\'ll get excellent visual quality when playing the latest games, with DLSS and ray-tracing support, but also the speed that only a fast CPU like the Ryzen 9 can provide.</p><p><a href=\"https://www.eurogamer.net/articles/2021-12-29-save-gbp200-on-this-packed-asus-gaming-laptop-with-an-rtx-3060\">Read more</a></p>', 'https://www.eurogamer.net/articles/2021-12-29-save-gbp200-on-this-packed-asus-gaming-laptop-with-an-rtx-3060'),
(1001, 'Eve Online announces Doctor Who crossover event where you fight Daleks', '2022-01-04', '<img src=\"https://images.gnwcdn.com/2022/articles/2022-01-04-15-58/eve-online-announces-doctor-who-crossover-event-where-you-can-fight-daleks-1641311932500.jpg/EG11/resize/1200x-1/2183172.jpg\" alt=\"\"/><p>Eve Online will host Doctor Who\'s most iconic enemies in an unprecedented crossover event, beginning next week on 13th January. </p><p>A teaser for the crossover - dubbed The Interstellar Convergence - appeared on Eve\'s YouTube channel this afternoon but offers few clues as to exactly what will happen.</p><p><a href=\"https://www.eurogamer.net/articles/2022-01-04-eve-online-announces-doctor-who-crossover-event-where-you-can-fight-daleks\">Read more</a></p>', 'https://www.eurogamer.net/articles/2022-01-04-eve-online-announces-doctor-who-crossover-event-where-you-can-fight-daleks');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
